CONTEXT = [
  DNS_HOSTNAME = "YES",
  NETWORK = "YES",
  SSH_PUBLIC_KEY = "${file("/baklava/id_rsa_baklava.pub")}",
  SET_HOSTNAME="§§NAME",
  USERNAME = "root" ]
CPU = "1.0"
VCPU = "2"
DISK = [
  DATASTORE = "local_images_ssd",
  DATASTORE_ID = "104",
  IMAGE_ID = "YOUR_IMAGE_ID" ]
GRAPHICS = [
  LISTEN = "0.0.0.0",
  TYPE = "VNC" ]
INPUTS_ORDER = ""
MEMORY = "4096"
MEMORY_UNIT_COST = "MB"
NIC = [
  NETWORK = "internet",
  NETWORK_UNAME = "oneadmin" ]
NIC = [
  NETWORK = "INTERNAL_NETWORK_NAME",
  NETWORK_UNAME = "NETWORK_USERNAME" ]
OS = [
  ARCH = "x86_64",
  BOOT = "" ]

